package wisp

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ContextFile is written on open and handed to the agent as its first read. It is regenerated
// every time, so deleting it is always safe.
func (c Config) ContextFile(item Item) string {
	return filepath.Join(c.ItemDir(item.Name), ".wisp-context.md")
}

// WriteContext renders the per-item context: the item's own notes, then for each repo in the
// manifest its branch, worktree, hub note and workspace doc. An item touching two repos pulls
// two repo contexts, not one per repo in the workspace.
//
// Every line is conditional. What it omits is what the agent will not know about.
func (c Config) WriteContext(item Item, entries []Entry) (string, error) {
	dir := c.ItemDir(item.Name)
	if !isDir(dir) {
		return "", nil
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Session context: %s\n\n", item.Name)
	b.WriteString("Generated by wisp. cwd is the workspace root, so every path below is relative to it.\n\n")

	b.WriteString("## This item\n\n")
	for _, f := range []string{"orchestration.md", "notes.md"} {
		if exists(filepath.Join(dir, f)) {
			fmt.Fprintf(&b, "- `%s/%s/%s`\n", c.Vault, item.Name, f)
		}
	}

	b.WriteString("\n## Repos in this item\n\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "### %s\n\n", e.Repo)
		fmt.Fprintf(&b, "- branch `%s`", e.Branch)
		if e.Base != "" {
			fmt.Fprintf(&b, " from `%s`", e.Base)
		}
		b.WriteString("\n")
		if wt := c.WorktreeFor(e.Repo, item); isDir(wt) {
			rel, _ := filepath.Rel(c.Workspace, wt)
			fmt.Fprintf(&b, "- worktree `%s`\n", rel)
		}
		if hub := filepath.Join(c.VaultDir(), e.Repo, e.Repo+".md"); exists(hub) {
			fmt.Fprintf(&b, "- hub note `%s/%s/%s.md`\n", c.Vault, e.Repo, e.Repo)
		}
		if doc := filepath.Join(c.Workspace, "docs", e.Repo+".md"); exists(doc) {
			fmt.Fprintf(&b, "- workspace doc `docs/%s.md`\n", e.Repo)
		}
		b.WriteString("\n")
	}

	out := c.ContextFile(item)
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return out, nil
}

// EnsureWorktrees reprovisions anything the manifest declares but disk lacks. Existing
// worktrees are skipped, so this is a no-op on re-open.
//
// It shells out rather than driving git directly: provision-worktree.sh already handles
// branching from the remote default, copying default.nix and .envrc, direnv allow and the
// dependency install, and duplicating that here would be a second source of truth.
func (c Config) EnsureWorktrees(item Item, entries []Entry, log func(string)) error {
	for _, e := range entries {
		wt := c.WorktreeFor(e.Repo, item)
		if isDir(wt) {
			continue
		}
		if !isDir(filepath.Join(c.Workspace, e.Repo)) {
			log(fmt.Sprintf("no such repo: %s", e.Repo))
			continue
		}
		if !exists(c.ProvisionPath()) {
			return fmt.Errorf("provisioning script missing: %s", c.ProvisionPath())
		}
		log(fmt.Sprintf("provisioning %s (%s)", e.Repo, e.Branch))

		// --attach always: the contract is "give me a worktree for this branch", and an item
		// reopened after cleanup has a live branch but no checkout. Without it, every
		// reconstitution fails on "branch already exists".
		args := []string{filepath.Join(c.Workspace, e.Repo), item.Slug(), e.Branch, "--attach"}
		if e.Base != "" {
			args = append(args, "--base", e.Base)
		}
		// No dependency install by default: nix and direnv still give a working toolchain, and
		// node_modules for a large monorepo is far too much to pay for opening an item to read.
		if !c.Install {
			args = append(args, "--no-install")
		}
		cmd := exec.Command(c.ProvisionPath(), args...)
		cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
		if err := cmd.Run(); err != nil {
			log(fmt.Sprintf("provisioning %s failed: %v", e.Repo, err))
		}
	}
	return nil
}

// Open reprovisions, writes context, builds the session if it is missing, then attaches.
func (c Config) Open(item Item, log func(string)) error {
	session := SessionFor(item.Name)

	if !HasSession(item.Name) {
		entries, err := c.Manifest(item)
		if err != nil {
			return err
		}
		if err := c.EnsureWorktrees(item, entries, log); err != nil {
			return err
		}
		ctx, err := c.WriteContext(item, entries)
		if err != nil {
			return err
		}

		// Window 0 is the agent, at the workspace root. One cwd sees the vault, docs, every
		// repo and every worktree, which is the whole point of the container model.
		program := c.Program
		if ctx != "" {
			rel, _ := filepath.Rel(c.Workspace, ctx)
			program = fmt.Sprintf("%s %q", c.Program,
				fmt.Sprintf("Working on item %s. Read %s first for the repos and notes in scope.", item.Name, rel))
		}
		if err := exec.Command("tmux", "new-session", "-d", "-s", session,
			"-n", "agent", "-c", c.Workspace, program).Run(); err != nil {
			return fmt.Errorf("could not create session: %w", err)
		}
		_ = exec.Command("tmux", "set-option", "-t", session, "history-limit", "10000").Run()
		_ = exec.Command("tmux", "set-option", "-t", session, ItemOption, item.Name).Run()

		// One shell window per repo worktree, for builds and dev servers. Not agents.
		for _, e := range entries {
			wt := c.WorktreeFor(e.Repo, item)
			if !isDir(wt) {
				continue
			}
			name := e.Repo
			if len(name) > 12 {
				name = name[:12]
			}
			_ = exec.Command("tmux", "new-window", "-t", session, "-n", name, "-c", wt).Run()
		}
		// By name, not index: base-index may be 1, so session:0 is not reliably the first window.
		_ = exec.Command("tmux", "select-window", "-t", session+":agent").Run()
	}

	return Attach(session)
}

// Attach hands the terminal over to the session, replacing this process.
func Attach(session string) error {
	tmuxPath, err := exec.LookPath("tmux")
	if err != nil {
		return err
	}
	var args []string
	if InsideTmux() {
		args = []string{"tmux", "switch-client", "-t", "=" + session}
	} else {
		// -u forces UTF-8 output to the client. Without it tmux only writes UTF-8 when the first
		// set variable of LC_ALL / LC_CTYPE / LANG contains "UTF-8", and on a bare SSH login none
		// of them is set. The symptom is misleading: the pane buffer holds correct UTF-8, so
		// capture-pane looks fine, but every multibyte glyph reaches the terminal mangled.
		args = []string{"tmux", "-u", "attach-session", "-t", "=" + session}
	}
	// Exec rather than spawn: wisp has nothing left to do, and staying alive would leave a
	// useless parent process wrapping the session for as long as it lives.
	return syscallExec(tmuxPath, args, os.Environ())
}
