package wisp

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ContextFile is written on open and handed to the agent as its first read. It is regenerated
// every time, so deleting it is always safe.
func (c Config) ContextFile(item Item) string {
	return filepath.Join(c.ItemDir(item.Name), ".wisp-context.md")
}

// WriteContext renders the per-item context: the item's own notes, then for each repo in the
// manifest its branch, worktree, hub note and workspace doc. An item touching two repos pulls
// two repo contexts, not one per repo in the workspace.
//
// Every line is conditional. What it omits is what the agent will not know about.
func (c Config) WriteContext(w Workflow, item Item, entries []Entry) (string, error) {
	dir := c.ItemDir(item.Name)
	if !isDir(dir) {
		return "", nil
	}
	if w.Hooks.Context != "" {
		body, err := c.runContextHook(w, item, entries)
		if err == nil {
			out := c.ContextFile(item)
			if werr := os.WriteFile(out, body, 0o644); werr != nil {
				return "", werr
			}
			return out, nil
		}
		// Falling back is the requirement, not a compromise. A session that will not open
		// because a docs script has a syntax error is a worse outcome than one that opens with
		// a generic briefing, and the error goes where a provisioning failure already goes.
		fmt.Fprintf(os.Stderr, "wisp: context hook failed, using the built-in briefing: %v\n", err)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Session context: %s\n\n", item.Name)
	b.WriteString("Generated by wisp. cwd is the workspace root, so every path below is relative to it.\n\n")

	b.WriteString("## This item\n\n")
	for _, f := range []string{"orchestration.md", "notes.md"} {
		if exists(filepath.Join(dir, f)) {
			fmt.Fprintf(&b, "- `%s/%s/%s`\n", c.Vault, item.Name, f)
		}
	}

	b.WriteString("\n## Repos in this item\n\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "### %s\n\n", e.Repo)
		fmt.Fprintf(&b, "- branch `%s`", e.Branch)
		if e.Base != "" {
			fmt.Fprintf(&b, " from `%s`", e.Base)
		}
		b.WriteString("\n")
		// The worktree is listed whether or not it exists yet. Provisioning runs in the
		// background so the session opens immediately, and the agent needs to know where the
		// checkout is going to be, not just where it already is.
		wt := c.WorktreeFor(w, e.Repo, item)
		rel, _ := filepath.Rel(c.Workspace, wt)
		if isDir(wt) {
			fmt.Fprintf(&b, "- worktree `%s`\n", rel)
		} else {
			fmt.Fprintf(&b, "- worktree `%s` (still provisioning, wait for it before building)\n", rel)
		}
		if hub := filepath.Join(c.VaultDir(), e.Repo, e.Repo+".md"); exists(hub) {
			fmt.Fprintf(&b, "- hub note `%s/%s/%s.md`\n", c.Vault, e.Repo, e.Repo)
		}
		if doc := filepath.Join(c.Workspace, "docs", e.Repo+".md"); exists(doc) {
			fmt.Fprintf(&b, "- workspace doc `docs/%s.md`\n", e.Repo)
		}
		b.WriteString("\n")
	}

	out := c.ContextFile(item)
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return out, nil
}

// contextRepo is one repo as the context hook sees it.
type contextRepo struct {
	Repo     string `json:"repo"`
	Branch   string `json:"branch"`
	Base     string `json:"base"`
	Worktree string `json:"worktree"`
	// Ready is the field a naive implementation forgets. Provisioning runs in the background, so
	// a worktree is described whether or not it exists yet and the hook has to be able to say
	// "this is where the checkout is going to be" rather than pointing at nothing.
	Ready bool `json:"ready"`
}

type contextInput struct {
	Item      string        `json:"item"`
	Workspace string        `json:"workspace"`
	Vault     string        `json:"vault"`
	Dir       string        `json:"dir"`
	Repos     []contextRepo `json:"repos"`
}

// runContextHook hands the item to the workflow's context script and takes its stdout as the
// briefing. Everything wisp already knows is on stdin, so the script does not have to re-derive
// any of it from the filesystem.
func (c Config) runContextHook(w Workflow, item Item, entries []Entry) ([]byte, error) {
	in := contextInput{
		Item:      item.Name,
		Workspace: c.Workspace,
		Vault:     c.Vault,
		Dir:       filepath.Join(c.Vault, item.Name),
	}
	for _, e := range entries {
		wt := c.WorktreeFor(w, e.Repo, item)
		rel, err := filepath.Rel(c.Workspace, wt)
		if err != nil {
			rel = wt
		}
		in.Repos = append(in.Repos, contextRepo{
			Repo: e.Repo, Branch: e.Branch, Base: e.Base, Worktree: rel, Ready: isDir(wt),
		})
	}
	payload, err := json.Marshal(in)
	if err != nil {
		return nil, err
	}
	body, err := c.runHook(w.Hooks.Context, payload)
	if err != nil {
		return nil, err
	}
	if len(bytes.TrimSpace(body)) == 0 {
		return nil, fmt.Errorf("%s printed nothing", w.Hooks.Context)
	}
	return body, nil
}

// runHook is the one place a workflow's script is executed.
//
// cwd is the workspace root and WISP_WORKSPACE is set, because that is the contract and because
// wisp's own cwd is wherever it was invoked from. stderr is captured rather than inherited so a
// failure can be reported as one line beside whatever wisp was doing, which is the difference
// between an annotated list and a mysteriously empty one. lastLine, shared with the ssh
// diagnosis in remote.go, is what a failing script gets to say: one line, because it goes
// somewhere with room for one.
func (c Config) runHook(script string, stdin []byte) ([]byte, error) {
	return c.runHookIn(script, stdin)
}

// runHookArgs is runHook with arguments and no stdin, for the source hook's --url mode.
func (c Config) runHookArgs(script string, args ...string) ([]byte, error) {
	return c.runHookIn(script, nil, args...)
}

func (c Config) runHookIn(script string, stdin []byte, args ...string) ([]byte, error) {
	if script == "" {
		return nil, errors.New("no hook")
	}
	cmd := exec.Command(script, args...)
	cmd.Dir = c.Workspace
	cmd.Env = append(os.Environ(), "WISP_WORKSPACE="+c.Workspace)
	if stdin != nil {
		cmd.Stdin = bytes.NewReader(stdin)
	}
	var out, errBuf bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errBuf
	if err := cmd.Run(); err != nil {
		if line := lastLine(errBuf.String()); line != "" {
			return out.Bytes(), fmt.Errorf("%s: %s", filepath.Base(script), line)
		}
		return out.Bytes(), fmt.Errorf("%s: %w", filepath.Base(script), err)
	}
	return out.Bytes(), nil
}

// EnsureWorktrees reprovisions anything the manifest declares but disk lacks. Existing
// worktrees are skipped, so this is a no-op on re-open.
//
// It shells out rather than driving git directly: provision-worktree.sh already handles
// branching from the remote default, copying default.nix and .envrc, direnv allow and the
// dependency install, and duplicating that here would be a second source of truth.
func (c Config) EnsureWorktrees(w Workflow, item Item, entries []Entry, log func(string)) error {
	script := w.Hooks.Provision
	for _, e := range entries {
		wt := c.WorktreeFor(w, e.Repo, item)
		if isDir(wt) {
			continue
		}
		if !isDir(filepath.Join(c.Workspace, e.Repo)) {
			log(fmt.Sprintf("no such repo: %s", e.Repo))
			continue
		}
		if script == "" {
			return fmt.Errorf("this workflow has no provisioning script, so there is nothing to build %s with", e.Repo)
		}
		if !exists(script) {
			return fmt.Errorf("provisioning script missing: %s", script)
		}
		log(fmt.Sprintf("provisioning %s (%s)", e.Repo, e.Branch))

		// --attach always: the contract is "give me a worktree for this branch", and an item
		// reopened after cleanup has a live branch but no checkout. Without it, every
		// reconstitution fails on "branch already exists".
		args := []string{filepath.Join(c.Workspace, e.Repo), item.Slug(), e.Branch, "--attach"}
		if e.Base != "" {
			args = append(args, "--base", e.Base)
		}
		// No dependency install by default: nix and direnv still give a working toolchain, and
		// node_modules for a large monorepo is far too much to pay for opening an item to read.
		if !c.Install {
			args = append(args, "--no-install")
		}
		cmd := exec.Command(script, args...)
		// Named rather than inherited: the contract says a hook runs at the workspace root, and
		// wisp's own cwd is wherever it was invoked from, which for the provision window is the
		// workspace but for a hand-run `wisp provision` is anywhere at all.
		cmd.Dir = c.Workspace
		cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
		if err := cmd.Run(); err != nil {
			log(fmt.Sprintf("provisioning %s failed: %v", e.Repo, err))
		}
	}
	return nil
}

// Open builds the session if it is missing, then attaches.
//
// Provisioning does NOT block this. It shells out to provision-worktree.sh, which pre-warms the
// nix environment via direnv, and a cold eval there takes long enough that waiting for it
// before showing the session felt like the tool had hung. The agent window needs none of it:
// it runs at the workspace root and reads the context file. So the session opens straight away
// and any missing worktrees are built in a side window that adds its own windows when done.
// oneShot is a --workflow given on the command line: it sits above every configured layer and
// is written nowhere, for "open this one with the review workflow, just this once".
func (c Config) Open(item Item, oneShot string, log func(string)) error {
	if c.IsRemote() {
		return c.openRemote(item)
	}

	// By identity, not by name: a session started by an older wisp is named differently but is
	// still this item's session, and creating a second one beside it would split the work.
	session := c.FindSession(item.Name)

	if session == "" {
		session = c.SessionName(item.Name)
		// An item picked straight off GitLab has never had a folder here. Make it now: the vault
		// is where its notes and its context file go, and without one WriteContext wrote nothing,
		// so the agent started with no prompt at all, not even the name of the item it was on.
		if !isDir(c.ItemDir(item.Name)) {
			if err := c.makeItemDir(item); err != nil {
				return fmt.Errorf("could not create the item folder: %w", err)
			}
		}
		// Resolved once, here, and threaded through: every layer below reads three files, and
		// resolving per repo in a loop would read them again for each one.
		w := c.WorkflowFor(item, oneShot)
		for _, note := range w.Notes {
			log(note)
		}
		entries, err := c.Manifest(w, item)
		if err != nil {
			return err
		}
		ctx, err := c.WriteContext(w, item, entries)
		if err != nil {
			return err
		}

		if err := c.buildLayout(w, session, item, entries, ctx); err != nil {
			return err
		}
		_ = exec.Command("tmux", "set-option", "-t", session, "history-limit", "10000").Run()
		_ = exec.Command("tmux", "set-option", "-t", session, ItemOption, item.Name).Run()
		// Which workspace this belongs to, so the other workspaces' pickers do not list it and
		// the tally in the header can attribute it.
		_ = exec.Command("tmux", "set-option", "-t", session, WSOption, c.Name).Run()
	}

	// Recorded before attaching, so a hop out of this workspace and back returns to this item.
	Remember(c.Name, session)
	return Attach(session)
}

// openRemote wraps the far side's session in a local one.
//
// The wrapper is an ordinary wisp session here, tagged with the item and the workspace, whose
// single window is an ssh into the machine that owns the work. That is what lets everything else
// stay unchanged: next and prev walk it, the workspace ring counts it, the last-visited session
// records it, and the needs-input check captures its pane, which is rendering the remote pane.
//
// Provisioning, the context file and the worktree windows are all the far side's business and
// happen there. This end only carries the terminal.
func (c Config) openRemote(item Item) error {
	session := c.FindSession(item.Name)
	if session == "" {
		session = c.SessionName(item.Name)
		// Somewhere that exists on this machine. The workspace path belongs to the other one.
		dir, err := os.UserHomeDir()
		if err != nil {
			dir = "/"
		}
		// The failure stays on screen. tmux closes a window the moment its command returns, so
		// an ssh that cannot connect would take the session with it and look exactly like wisp
		// creating nothing at all.
		line := fmt.Sprintf("%s || { echo; echo 'connection to %s ended; press enter'; read -r _; }",
			c.Location.SSHLine(true, "open", item.Name), c.Location.Host)
		if err := exec.Command("tmux", "new-session", "-d", "-s", session,
			"-n", c.Location.Host, "-c", dir, line).Run(); err != nil {
			return fmt.Errorf("could not create session: %w", err)
		}
		_ = exec.Command("tmux", "set-option", "-t", session, "history-limit", "10000").Run()
		_ = exec.Command("tmux", "set-option", "-t", session, ItemOption, item.Name).Run()
		_ = exec.Command("tmux", "set-option", "-t", session, WSOption, c.Name).Run()
		// Said in the status bar rather than only known: two tmux servers are now stacked and
		// the prefix key means two things, which is worth seeing rather than discovering.
		_ = exec.Command("tmux", "set-option", "-t", session, "status", "on").Run()
		_ = exec.Command("tmux", "set-option", "-t", session, "status-right",
			fmt.Sprintf(" %s:%s ", c.Name, c.Location.Host)).Run()
	}
	Remember(c.Name, session)
	return Attach(session)
}

// maxInlineContext bounds what gets pasted into the startup prompt. Real context files are a
// few hundred bytes; anything past this is unusual enough to be worth a read instead.
const maxInlineContext = 8 << 10

// startupPrompt is the agent's opening message.
//
// The context is inlined rather than pointed at. Telling the agent to read the file costs a
// full tool-call round trip before it can start, several seconds of latency to fetch a file
// that is typically under 300 bytes. The path is still named at the end, since the file is
// regenerated when provisioning finishes and is worth re-reading then.
func (c Config) startupPrompt(item Item, ctxPath string) string {
	if ctxPath == "" {
		return ""
	}
	rel, _ := filepath.Rel(c.Workspace, ctxPath)
	body, err := os.ReadFile(ctxPath)
	if err != nil || len(body) > maxInlineContext {
		return fmt.Sprintf("Working on item %s. Read %s first for the repos and notes in scope.", item.Name, rel)
	}
	return fmt.Sprintf(`Working on item %s. Your context follows; you do not need to read it from disk.

%s
(That is %s, regenerated whenever wisp opens this item. Re-read it if a worktree was still provisioning.)`,
		item.Name, strings.TrimSpace(string(body)), rel)
}

// shellQuote wraps a string for /bin/sh. Single quotes rather than Go's %q, because the prompt
// is multi-line: inside double quotes the shell would pass a literal backslash-n through to the
// agent instead of a newline.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// pane is one concrete window: a layout entry with its templates expanded and its worktree, if
// it had one, decided.
type pane struct {
	name  string
	dir   string
	run   string
	focus bool
}

// expandLayout turns the workflow's layout into the windows this particular open will create.
//
// Two entries are conditional and everything else is unconditional: `for: each-worktree` becomes
// one window per worktree that exists, and `when: provisioning` appears only while one does not.
// That is the whole control flow, deliberately: anything wanting more should be a script.
func (c Config) expandLayout(w Workflow, item Item, entries []Entry, ctx string) []pane {
	prompt := c.startupPrompt(item, ctx)
	self, _ := os.Executable()
	home, err := os.UserHomeDir()
	if err != nil {
		home = "/"
	}

	present := 0
	for _, e := range entries {
		if isDir(c.WorktreeFor(w, e.Repo, item)) {
			present++
		}
	}
	provisioning := present < len(entries)

	base := map[string]string{
		"item":      item.Name,
		"slug":      item.Slug(),
		"workspace": c.Workspace,
		"program":   w.Program,
		"prompt":    prompt,
		"wisp":      self,
	}
	dirFor := func(kind, worktree string) string {
		switch kind {
		case "worktree":
			if worktree != "" {
				return worktree
			}
			// A layout entry asking for a worktree outside a per-worktree window has no
			// checkout to mean. The workspace root is the honest answer rather than an error.
			return c.Workspace
		case "home":
			return home
		default:
			return c.Workspace
		}
	}

	var out []pane
	for _, win := range w.Layout {
		if win.When == "provisioning" && !provisioning {
			continue
		}
		if win.For == "each-worktree" {
			for _, e := range entries {
				wt := c.WorktreeFor(w, e.Repo, item)
				if !isDir(wt) {
					continue // the provisioning window adds these once the checkout lands
				}
				vars := maps.Clone(base)
				vars["repo"], vars["branch"], vars["base"], vars["worktree"] = e.Repo, e.Branch, e.Base, wt
				out = append(out, pane{
					name:  windowName(Expand(win.Window, vars)),
					dir:   dirFor(win.Cwd, wt),
					run:   Expand(win.Run, shellVars(vars)),
					focus: win.Focus,
				})
			}
			continue
		}
		out = append(out, pane{
			name:  windowName(Expand(win.Window, base)),
			dir:   dirFor(win.Cwd, ""),
			run:   Expand(win.Run, shellVars(base)),
			focus: win.Focus,
		})
	}
	return out
}

// shellVars is the substitution set for `run:`, which is handed to /bin/sh.
//
// Every value is quoted except the program, because a run line is a shell command and these are
// data going into it. It matters more than it looks: an item name can come from a source hook,
// which is a program somebody else wrote, and before this every one of these was substituted
// raw, so a name holding a semicolon was a command wisp would run for you.
//
// `program` stays unquoted on purpose. It has always been a command line rather than a path, so
// `claude --permission-mode auto` has to keep working, and quoting it would look for a binary
// with a space in its name.
func shellVars(vars map[string]string) map[string]string {
	out := make(map[string]string, len(vars))
	for k, v := range vars {
		if k == "program" {
			out[k] = v
			continue
		}
		out[k] = shellQuote(v)
	}
	return out
}

// windowName trims a name to what tmux window names have always been here. An expanded template
// can produce anything, including nothing, and a window with no name is not creatable.
func windowName(s string) string {
	s = strings.TrimSpace(s)
	if len(s) > 12 {
		s = s[:12]
	}
	if s == "" {
		s = "window"
	}
	return s
}

// buildLayout creates the session and its windows from the expanded layout.
//
// The first window has to come from new-session, because that is the only way tmux makes one, so
// the layout's order decides which window the session is built around rather than a compiled-in
// assumption that window 0 is the agent.
func (c Config) buildLayout(w Workflow, session string, item Item, entries []Entry, ctx string) error {
	panes := c.expandLayout(w, item, entries, ctx)
	if len(panes) == 0 {
		// Nothing to build usually means a layout of nothing but per-worktree windows and no
		// worktrees yet. A session with no windows cannot exist, so open a shell at the root:
		// an unexpected layout should still leave you somewhere you can work.
		panes = []pane{{name: "agent", dir: c.Workspace}}
	}

	first := panes[0]
	args := []string{"new-session", "-d", "-s", session, "-n", first.name, "-c", first.dir}
	if first.run != "" {
		args = append(args, first.run)
	}
	if err := exec.Command("tmux", args...).Run(); err != nil {
		return fmt.Errorf("could not create session: %w", err)
	}
	for _, p := range panes[1:] {
		// -d so the session does not walk its focus to each window as it is built.
		a := []string{"new-window", "-t", session, "-d", "-n", p.name, "-c", p.dir}
		if p.run != "" {
			a = append(a, p.run)
		}
		_ = exec.Command("tmux", a...).Run()
	}

	// By name, not index: base-index may be 1, so session:0 is not reliably the first window.
	focus := first.name
	for _, p := range panes {
		if p.focus {
			focus = p.name
			break
		}
	}
	_ = exec.Command("tmux", "select-window", "-t", session+":"+focus).Run()
	return nil
}

// addWorktreeWindows creates the windows a layout's per-worktree entries want, skipping any that
// already exist, and returns how many worktrees are present. Safe to call twice: ProvisionItem
// calls it again once the checkouts exist, which is the whole reason it is separate from
// buildLayout.
func (c Config) addWorktreeWindows(w Workflow, session string, item Item, entries []Entry) int {
	existing := map[string]bool{}
	if out, err := tmux("list-windows", "-t", session, "-F", "#{window_name}"); err == nil {
		for _, name := range strings.Split(out, "\n") {
			existing[name] = true
		}
	}
	present := 0
	for _, e := range entries {
		if isDir(c.WorktreeFor(w, e.Repo, item)) {
			present++
		}
	}
	// Only the per-worktree entries. Everything else was created when the session was, and
	// making them again would put a second agent window beside the one already running.
	only := w
	only.Layout = nil
	for _, win := range w.Layout {
		if win.For == "each-worktree" {
			only.Layout = append(only.Layout, win)
		}
	}
	for _, p := range c.expandLayout(only, item, entries, "") {
		if existing[p.name] {
			continue
		}
		a := []string{"new-window", "-t", session, "-d", "-n", p.name, "-c", p.dir}
		if p.run != "" {
			a = append(a, p.run)
		}
		_ = exec.Command("tmux", a...).Run()
	}
	return present
}

// ProvisionItem is the background half of Open: build the missing worktrees, then add their windows
// and refresh the context file so it no longer says "still provisioning". Run in its own tmux
// window by Open; also useful by hand after deleting a worktree.
func (c Config) ProvisionItem(item Item, log func(string)) error {
	w := c.WorkflowFor(item, "")
	for _, note := range w.Notes {
		log(note)
	}
	entries, err := c.Manifest(w, item)
	if err != nil {
		return err
	}
	if err := c.EnsureWorktrees(w, item, entries, log); err != nil {
		return err
	}
	if session := c.FindSession(item.Name); session != "" {
		c.addWorktreeWindows(w, session, item, entries)
	}
	// Rewritten now that the checkouts exist, so an agent re-reading it sees real paths.
	_, err = c.WriteContext(w, item, entries)
	return err
}

// Attach hands the terminal over to the session, replacing this process.
func Attach(session string) error {
	tmuxPath, err := exec.LookPath("tmux")
	if err != nil {
		return err
	}
	var args []string
	if InsideTmux() {
		args = []string{"tmux", "switch-client", "-t", "=" + session}
	} else {
		// -u forces UTF-8 output to the client. Without it tmux only writes UTF-8 when the first
		// set variable of LC_ALL / LC_CTYPE / LANG contains "UTF-8", and on a bare SSH login none
		// of them is set. The symptom is misleading: the pane buffer holds correct UTF-8, so
		// capture-pane looks fine, but every multibyte glyph reaches the terminal mangled.
		args = []string{"tmux", "-u", "attach-session", "-t", "=" + session}
	}
	// Exec rather than spawn: wisp has nothing left to do, and staying alive would leave a
	// useless parent process wrapping the session for as long as it lives.
	return syscallExec(tmuxPath, args, os.Environ())
}
