package wisp

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ContextFile is written on open and handed to the agent as its first read. It is regenerated
// every time, so deleting it is always safe.
func (c Config) ContextFile(item Item) string {
	return filepath.Join(c.ItemDir(item.Name), ".wisp-context.md")
}

// WriteContext renders the per-item context: the item's own notes, then for each repo in the
// manifest its branch, worktree, hub note and workspace doc. An item touching two repos pulls
// two repo contexts, not one per repo in the workspace.
//
// Every line is conditional. What it omits is what the agent will not know about.
func (c Config) WriteContext(item Item, entries []Entry) (string, error) {
	dir := c.ItemDir(item.Name)
	if !isDir(dir) {
		return "", nil
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Session context: %s\n\n", item.Name)
	b.WriteString("Generated by wisp. cwd is the workspace root, so every path below is relative to it.\n\n")

	b.WriteString("## This item\n\n")
	for _, f := range []string{"orchestration.md", "notes.md"} {
		if exists(filepath.Join(dir, f)) {
			fmt.Fprintf(&b, "- `%s/%s/%s`\n", c.Vault, item.Name, f)
		}
	}

	b.WriteString("\n## Repos in this item\n\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "### %s\n\n", e.Repo)
		fmt.Fprintf(&b, "- branch `%s`", e.Branch)
		if e.Base != "" {
			fmt.Fprintf(&b, " from `%s`", e.Base)
		}
		b.WriteString("\n")
		// The worktree is listed whether or not it exists yet. Provisioning runs in the
		// background so the session opens immediately, and the agent needs to know where the
		// checkout is going to be, not just where it already is.
		wt := c.WorktreeFor(e.Repo, item)
		rel, _ := filepath.Rel(c.Workspace, wt)
		if isDir(wt) {
			fmt.Fprintf(&b, "- worktree `%s`\n", rel)
		} else {
			fmt.Fprintf(&b, "- worktree `%s` (still provisioning, wait for it before building)\n", rel)
		}
		if hub := filepath.Join(c.VaultDir(), e.Repo, e.Repo+".md"); exists(hub) {
			fmt.Fprintf(&b, "- hub note `%s/%s/%s.md`\n", c.Vault, e.Repo, e.Repo)
		}
		if doc := filepath.Join(c.Workspace, "docs", e.Repo+".md"); exists(doc) {
			fmt.Fprintf(&b, "- workspace doc `docs/%s.md`\n", e.Repo)
		}
		b.WriteString("\n")
	}

	out := c.ContextFile(item)
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return out, nil
}

// EnsureWorktrees reprovisions anything the manifest declares but disk lacks. Existing
// worktrees are skipped, so this is a no-op on re-open.
//
// It shells out rather than driving git directly: provision-worktree.sh already handles
// branching from the remote default, copying default.nix and .envrc, direnv allow and the
// dependency install, and duplicating that here would be a second source of truth.
func (c Config) EnsureWorktrees(item Item, entries []Entry, log func(string)) error {
	for _, e := range entries {
		wt := c.WorktreeFor(e.Repo, item)
		if isDir(wt) {
			continue
		}
		if !isDir(filepath.Join(c.Workspace, e.Repo)) {
			log(fmt.Sprintf("no such repo: %s", e.Repo))
			continue
		}
		if !exists(c.ProvisionPath()) {
			return fmt.Errorf("provisioning script missing: %s", c.ProvisionPath())
		}
		log(fmt.Sprintf("provisioning %s (%s)", e.Repo, e.Branch))

		// --attach always: the contract is "give me a worktree for this branch", and an item
		// reopened after cleanup has a live branch but no checkout. Without it, every
		// reconstitution fails on "branch already exists".
		args := []string{filepath.Join(c.Workspace, e.Repo), item.Slug(), e.Branch, "--attach"}
		if e.Base != "" {
			args = append(args, "--base", e.Base)
		}
		// No dependency install by default: nix and direnv still give a working toolchain, and
		// node_modules for a large monorepo is far too much to pay for opening an item to read.
		if !c.Install {
			args = append(args, "--no-install")
		}
		cmd := exec.Command(c.ProvisionPath(), args...)
		cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
		if err := cmd.Run(); err != nil {
			log(fmt.Sprintf("provisioning %s failed: %v", e.Repo, err))
		}
	}
	return nil
}

// Open builds the session if it is missing, then attaches.
//
// Provisioning does NOT block this. It shells out to provision-worktree.sh, which pre-warms the
// nix environment via direnv, and a cold eval there takes long enough that waiting for it
// before showing the session felt like the tool had hung. The agent window needs none of it:
// it runs at the workspace root and reads the context file. So the session opens straight away
// and any missing worktrees are built in a side window that adds its own windows when done.
func (c Config) Open(item Item, log func(string)) error {
	session := SessionFor(item.Name)

	if !HasSession(item.Name) {
		entries, err := c.Manifest(item)
		if err != nil {
			return err
		}
		ctx, err := c.WriteContext(item, entries)
		if err != nil {
			return err
		}

		// Window 0 is the agent, at the workspace root. One cwd sees the vault, docs, every
		// repo and every worktree, which is the whole point of the container model.
		program := c.Program
		if prompt := c.startupPrompt(item, ctx); prompt != "" {
			program = c.Program + " " + shellQuote(prompt)
		}
		if err := exec.Command("tmux", "new-session", "-d", "-s", session,
			"-n", "agent", "-c", c.Workspace, program).Run(); err != nil {
			return fmt.Errorf("could not create session: %w", err)
		}
		_ = exec.Command("tmux", "set-option", "-t", session, "history-limit", "10000").Run()
		_ = exec.Command("tmux", "set-option", "-t", session, ItemOption, item.Name).Run()

		// One shell window per worktree that already exists, for builds and dev servers.
		if c.addWorktreeWindows(session, item, entries) < len(entries) {
			// Something still needs provisioning. Do it in its own window so the work is
			// visible and interruptible rather than hidden behind a frozen picker. The window
			// closes itself when the command finishes.
			if self, err := os.Executable(); err == nil {
				_ = exec.Command("tmux", "new-window", "-t", session, "-n", "provision",
					"-c", c.Workspace, fmt.Sprintf("%q provision %q", self, item.Name)).Run()
			}
		}
		// By name, not index: base-index may be 1, so session:0 is not reliably the first window.
		_ = exec.Command("tmux", "select-window", "-t", session+":agent").Run()
	}

	return Attach(session)
}

// maxInlineContext bounds what gets pasted into the startup prompt. Real context files are a
// few hundred bytes; anything past this is unusual enough to be worth a read instead.
const maxInlineContext = 8 << 10

// startupPrompt is the agent's opening message.
//
// The context is inlined rather than pointed at. Telling the agent to read the file costs a
// full tool-call round trip before it can start, several seconds of latency to fetch a file
// that is typically under 300 bytes. The path is still named at the end, since the file is
// regenerated when provisioning finishes and is worth re-reading then.
func (c Config) startupPrompt(item Item, ctxPath string) string {
	if ctxPath == "" {
		return ""
	}
	rel, _ := filepath.Rel(c.Workspace, ctxPath)
	body, err := os.ReadFile(ctxPath)
	if err != nil || len(body) > maxInlineContext {
		return fmt.Sprintf("Working on item %s. Read %s first for the repos and notes in scope.", item.Name, rel)
	}
	return fmt.Sprintf(`Working on item %s. Your context follows; you do not need to read it from disk.

%s
(That is %s, regenerated whenever wisp opens this item. Re-read it if a worktree was still provisioning.)`,
		item.Name, strings.TrimSpace(string(body)), rel)
}

// shellQuote wraps a string for /bin/sh. Single quotes rather than Go's %q, because the prompt
// is multi-line: inside double quotes the shell would pass a literal backslash-n through to the
// agent instead of a newline.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// addWorktreeWindows creates one window per existing worktree, skipping any that already have
// one, and returns how many worktrees are present. Safe to call twice: Provision calls it again
// once the checkouts exist.
func (c Config) addWorktreeWindows(session string, item Item, entries []Entry) int {
	existing := map[string]bool{}
	if out, err := tmux("list-windows", "-t", session, "-F", "#{window_name}"); err == nil {
		for _, w := range strings.Split(out, "\n") {
			existing[w] = true
		}
	}
	present := 0
	for _, e := range entries {
		wt := c.WorktreeFor(e.Repo, item)
		if !isDir(wt) {
			continue
		}
		present++
		name := e.Repo
		if len(name) > 12 {
			name = name[:12]
		}
		if existing[name] {
			continue
		}
		_ = exec.Command("tmux", "new-window", "-t", session, "-d", "-n", name, "-c", wt).Run()
	}
	return present
}

// ProvisionItem is the background half of Open: build the missing worktrees, then add their windows
// and refresh the context file so it no longer says "still provisioning". Run in its own tmux
// window by Open; also useful by hand after deleting a worktree.
func (c Config) ProvisionItem(item Item, log func(string)) error {
	entries, err := c.Manifest(item)
	if err != nil {
		return err
	}
	if err := c.EnsureWorktrees(item, entries, log); err != nil {
		return err
	}
	session := SessionFor(item.Name)
	if hasRawSession(session) {
		c.addWorktreeWindows(session, item, entries)
	}
	// Rewritten now that the checkouts exist, so an agent re-reading it sees real paths.
	_, err = c.WriteContext(item, entries)
	return err
}

// Attach hands the terminal over to the session, replacing this process.
func Attach(session string) error {
	tmuxPath, err := exec.LookPath("tmux")
	if err != nil {
		return err
	}
	var args []string
	if InsideTmux() {
		args = []string{"tmux", "switch-client", "-t", "=" + session}
	} else {
		// -u forces UTF-8 output to the client. Without it tmux only writes UTF-8 when the first
		// set variable of LC_ALL / LC_CTYPE / LANG contains "UTF-8", and on a bare SSH login none
		// of them is set. The symptom is misleading: the pane buffer holds correct UTF-8, so
		// capture-pane looks fine, but every multibyte glyph reaches the terminal mangled.
		args = []string{"tmux", "-u", "attach-session", "-t", "=" + session}
	}
	// Exec rather than spawn: wisp has nothing left to do, and staying alive would leave a
	// useless parent process wrapping the session for as long as it lives.
	return syscallExec(tmuxPath, args, os.Environ())
}
